GET http://localhost:4000/users

###

POST http://localhost:4000/register
Content-Type: application/json

{
  "name": "deep",
  "password": "deep@123"
}

### 

POST http://localhost:4000/login
Content-Type: application/json

{
  "name": "noddy",
  "password": "noddy@123"
}