### get user list

GET http://localhost:3000/users

### get post list

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGVlcCIsImlhdCI6MTY2Njg0NzQwNywiZXhwIjoxNjY2ODQ3NDI3fQ.bOGa24OWsMLSL8-fToVEhTKALkB0xCY2AHRy3kYFDTg

### refresh token

POST http://localhost:3000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGVlcCIsImlhdCI6MTY2Njg0NzM1NX0.rzHTixL99Dr2AwuVcUSvtFfqtVpihM665qad9VBKWTo"
}

### delete token

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGVlcCIsImlhdCI6MTY2Njg0NzM1NX0.rzHTixL99Dr2AwuVcUSvtFfqtVpihM665qad9VBKWTo"
}

### create user

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "deep",
    "password": "deep@123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "deep",
    "password": "deep@123"
}