### get user list

GET http://localhost:3000/users

### get post list

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibm9kZHkiLCJpYXQiOjE2NjY4NDI2NzN9.h61VnAG0L_HFJCMnRUAS6qNT-ALdilK3VRY3zhWJjV8

### create user

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "noddy",
    "password": "noddy@123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "noddy",
    "password": "noddy@123"
}