### get user list

GET http://localhost:3000/users

### get post list

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGVlcCIsImlhdCI6MTY2Njg0MjgwNH0.AP21BHiFzmqSkdn7DPyZMczIqlYv0z9IVKR-ZLQEPcY

### create user

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "noddy",
    "password": "noddy@123"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "noddy",
    "password": "noddy@123"
}